services:
  app:
    build: .
    restart: 'unless-stopped'
    user: app:app
    logging:
        driver: "json-file"
        options:
            max-size: "100m"
            max-file: "5"
    volumes:
      - ./.env:/app/.env
      - ./auth:/app/auth
      - ./logs/:/app/logs
